# Generated by Django 5.2.5 on 2025-08-30 14:03

import django.core.validators
import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_label', models.CharField(help_text='College-specific unique label used for internal lookup.', max_length=80, unique=True)),
                ('asset_tag', models.CharField(help_text='Physical asset/inventory tag.', max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, help_text='Device serial number (unique when known).', max_length=100, null=True, unique=True)),
                ('make', models.CharField(help_text='Manufacturer, e.g., Toshiba, Lexmark', max_length=80)),
                ('model', models.CharField(help_text='Model, e.g., e-STUDIO 3515AC, M3150', max_length=120)),
                ('building', models.CharField(help_text='Building name, e.g., Hutchins Library', max_length=120)),
                ('location_in_building', models.CharField(help_text='Room/area, e.g., 1st Floor Near Circulation', max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IPv4 or IPv6; optional if DHCP/unassigned.', null=True, unpack_ipv4=True)),
                ('mac_address', models.CharField(help_text='Physical NIC MAC, unique per device (e.g., 00:11:22:33:44:55).', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., 00:11:22:33:44:55).', regex='^([0-9A-Fa-f]{2}([-:])){5}([0-9A-Fa-f]{2})$')])),
                ('qr_token', models.CharField(default=tickets.models.default_qr_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_tag'], name='tickets_pri_asset_t_c0b464_idx'), models.Index(fields=['building'], name='tickets_pri_buildin_618a1d_idx'), models.Index(fields=['location_in_building'], name='tickets_pri_locatio_cb468d_idx'), models.Index(fields=['make'], name='tickets_pri_make_1e56c7_idx'), models.Index(fields=['model'], name='tickets_pri_model_a889dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUPPLY', 'Supply'), ('ISSUE', 'Issue')], max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('FULFILLED', 'Fulfilled'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.printer')),
            ],
        ),
    ]
