# Generated by Django 5.2.5 on 2025-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('toner', 'Toner'), ('staple', 'Staple'), ('waste_basket', 'Waste Basket')], max_length=50)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=1)),
                ('compatible_printers', models.ManyToManyField(blank=True, to='tickets.printer')),
            ],
        ),
    ]
