# Generated by Django 5.2.5 on 2025-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='model_number',
            field=models.CharField(blank=True, help_text="Exact model/part number, e.g., 'T-FC415K'", max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text="User-friendly name, e.g., 'Toshiba color black toner'", max_length=100),
        ),
    ]
