# Generated by Django 5.2.6 on 2025-09-14 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_printercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='asset_tag',
            field=models.CharField(help_text='Physical asset/inventory tag.', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='campus_label',
            field=models.CharField(help_text='College-specific unique label used for internal lookup.', max_length=80),
        ),
        migrations.AlterField(
            model_name='printer',
            name='mac_address',
            field=models.CharField(help_text='Physical NIC MAC, unique per device (e.g., 00:11:22:33:44:55).', max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., 00:11:22:33:44:55).', regex='^([0-9A-Fa-f]{2}([-:])){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number (unique when known).', max_length=100, null=True),
        ),
    ]
