# Generated by Django 5.2.5 on 2025-09-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_printer_asset_tag_alter_printer_campus_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('building', models.CharField(blank=True, help_text='Optional building name if different from group name.', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('group_order_allowed_emails', models.TextField(blank=True, help_text='Comma or newline separated list of email addresses allowed to place group-wide orders. Leave blank to allow any requester.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='requestticket',
            name='applies_to_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Logical grouping (e.g., building) for supply/issue management.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='tickets.printergroup'),
        ),
        migrations.AddField(
            model_name='requestticket',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.printergroup'),
        ),
    ]
