# Generated by Django 5.2.5 on 2025-09-28 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_printergroup_requestticket_applies_to_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printergroup',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Users allowed to manage printers in this group.', related_name='managed_printer_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
