"""
Django settings for printer_system project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
try:
    import dj_database_url  # type: ignore
    HAVE_DJ_DB_URL = True
except Exception:
    HAVE_DJ_DB_URL = False

# Optional dependencies flags
try:
    import whitenoise  # type: ignore
    HAVE_WHITENOISE = True
except Exception:
    HAVE_WHITENOISE = False

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env if present
env_path = BASE_DIR / ".env"
if env_path.exists():
    load_dotenv(env_path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Safer default: DEBUG is false unless explicitly enabled via environment.
DEBUG = os.getenv("DEBUG", "false").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# Require SECRET_KEY via environment unless in explicit DEBUG mode.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-insecure-secret-key"
    else:
        raise RuntimeError(
            "SECRET_KEY is not set. Set SECRET_KEY in the environment or enable DEBUG=true for local dev."
        )

# Hosts configuration: read from env (comma-separated). If unset, allow all in
# DEBUG mode for local development, and require explicit hosts in production.
_ALLOWED_HOSTS_RAW = os.getenv("ALLOWED_HOSTS", "").strip()
if _ALLOWED_HOSTS_RAW:
    ALLOWED_HOSTS = [h.strip() for h in _ALLOWED_HOSTS_RAW.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['*'] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    'import_export',
    'tickets.apps.TicketsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise (if installed) will be inserted just after SecurityMiddleware below.
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'tickets.middleware.IssueSummaryMiddleware',
    'tickets.middleware.SlowRequestLoggingMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Insert Whitenoise middleware if available
if HAVE_WHITENOISE:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'printer_system.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],   # project-level templates folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'printer_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}

# If DATABASE_URL is set, prefer it (e.g., DigitalOcean Managed Postgres)
_DB_URL = os.getenv('DATABASE_URL', '').strip()
if _DB_URL and HAVE_DJ_DB_URL:
    _conn_max_age = int(os.getenv('DB_CONN_MAX_AGE', '600') or '600')
    _ssl_require = os.getenv('DB_SSL_REQUIRE', 'true').strip().lower() == 'true'
    DATABASES['default'] = dj_database_url.parse(_DB_URL, conn_max_age=_conn_max_age, ssl_require=_ssl_require)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Public URL
STATIC_URL = '/static/'

# Collect static files here for production deployments
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use compressed, hashed files when collected (only if Whitenoise is installed)
if HAVE_WHITENOISE:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings - during development, print to console
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@berea.local")

# Comma-separated list to Python list
EMAIL_TO = [e.strip() for e in os.getenv("EMAIL_TO", "").split(",") if e.strip()]



ISSUE_SUMMARY_RECIPIENT = (
    os.getenv("ISSUE_SUMMARY_RECIPIENT", "").strip()
    or (EMAIL_TO[0] if EMAIL_TO else "sklarz@berea.edu")
)



ISSUE_SUMMARY_INTERVAL_HOURS = int(os.getenv("ISSUE_SUMMARY_INTERVAL_HOURS", "24"))

ISSUE_SUMMARY_INTERVAL = timedelta(hours=ISSUE_SUMMARY_INTERVAL_HOURS)

ISSUE_SUMMARY_INCLUDE_CLOSED = os.getenv("ISSUE_SUMMARY_INCLUDE_CLOSED", "false").lower() == "true"

_LOOKBACK = os.getenv("ISSUE_SUMMARY_LOOKBACK_HOURS", "").strip()

ISSUE_SUMMARY_LOOKBACK_HOURS = int(_LOOKBACK) if _LOOKBACK else None




# --- SNMP / Device Status ---
# Values are read from .env and surfaced as Django settings so
# tickets.snmp_client and related code can access them via settings.
SNMP_COMMUNITY = os.getenv("SNMP_COMMUNITY", "public")
SNMP_TIMEOUT = int(os.getenv("SNMP_TIMEOUT", "5"))
SNMP_RETRIES = int(os.getenv("SNMP_RETRIES", "1"))
SNMP_POLL_INTERVAL_SECONDS = int(os.getenv("SNMP_POLL_INTERVAL_SECONDS", "300"))





LOGIN_URL = 'admin:login'
LOGOUT_REDIRECT_URL = 'admin:login'

# --- Reverse proxy / HTTPS / CSRF ---
# Ensure Django recognizes HTTPS when behind a proxy (e.g., DigitalOcean App Platform)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Secure cookies in non-debug environments
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Parse trusted origins for CSRF validation (comma-separated, include scheme)
_CSRF_TRUSTED_ORIGINS_RAW = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
if _CSRF_TRUSTED_ORIGINS_RAW:
    CSRF_TRUSTED_ORIGINS = [v.strip() for v in _CSRF_TRUSTED_ORIGINS_RAW.split(',') if v.strip()]

